### ISSUE TITLE
Generate interactive d3 to show colormaps

### ISSUE THREAD

**Issue by vsoch** [vsoch/codeart#1]
I should be able to parse a language (or other logical grouping of files), generate color vectors and counts, and then save to an interactive d3 grid, where I am able to mouse over the different groups to see the values change (in transparency) based on the relevance to the particular group.

**Comment by abitrolly** [comment]
Is it possible to do this in plain TkInter? With the advantage of not needing many mbytes of browser just to see the vis.
```python
from tkinter import *

window = Tk()
window.title('netcanvas')

c = Canvas(window, width=400, height=300)
c.pack()  # TODO: ???

# --- monkeypatching to Processing-like API
c.rect = c.create_rectangle
# TODO: write an article with difference of
# box model in drawing API of processing vs
# TkInter

def box(x, y, size=10):
  # TODO: box model for create_rectangle
  # (0, 0, 10) - box 10px wide without left and top border
  # (1, 1, 10) - box 11px wide with left and right border
  c.rect(x, y, x+size, y+size) #, fill="blue")

c.box = box
# /--
  

def draw(w):
  # draw grid
  for x in range(0, 400, 10):
    for y in range (0, 300, 10):
        box(x,y)
  
draw(c)
mainloop()
```

**Comment by vsoch** [comment]
Tkinter is usually a GUI program, the reason for it would be to replace the browser. I don't see why not, but I prefer to have the browser for interactive visualization (and easy deployment for others to see on the web). For example, here is a [quick prototype](https://vsoch.github.io/codeart-examples/parse_repo/web/) of visualizing all extensions for the spack/spack repository - you can click on an extension to see the relevant terms. And of course the use of extensions is arbitrary, the same could be done for [years for example](https://vsoch.github.io/codeart-examples/parse_by_year/). I'm currently working on a better organization of the colors using monte carlo.You'll also notice that the second link is heavier on the browser, and this is because d3 tends to slow down when you go over too many objects in the DOM. For the one I'm working on now, I am going to try to use canvas instead.

If you want to put something together as an example (in the examples repo I linked) using Tkinter, I'd be happy to help and include it! I haven't even released the next version of codeart (beyong the very basic first release) because I'm right in the middle of development - I want to finish this particular visualization (with canvas) and then have one more example that uses the palette of a code base to generate other art. Then that should be enough to write it up and share. :)

But yes, happy to help with the Tkinter example, if you can be clear about what you are trying to do. See https://github.com/vsoch/codeart-examples for where to add it (as a folder with description in the README).

**Comment by vsoch** [comment]
And another side note - I'm testing out plotting images with Web Assembly and rust, because (supposedly) it might work really efficiently! I'm pretty much just experimenting / having fun at this point because I'm not great at either of those two things, haha.

**Comment by abitrolly** [comment]
> https://vsoch.github.io/codeart-examples/parse_repo/web/

This one is nice, and yes - it is lagging in FF 71. I abandoned `d3.js` exactly because of this slowness few years ago, but my case is different - I need a real-time visualizer of how SCons creates objects in its build tree - https://github.com/yakshaveinc/tasks/issues/50 and the second problem is that I couldn't find a way to pipe events from SCons process to browser page, or the browser page to request them. The flow of messages from SCons to this `netcanvas` is supposed to be UDP to avoid locks on waiting for TCP delivery confirmations.

As for Rust + WebAssemble, the best labour of love that I've seen recently are notes linked from this post https://users.rust-lang.org/t/writing-a-213-byte-webassembly-graphics-demo-with-rust/29099 - it comes with a lot of very low level details, and it is also very rewarding in this regard. )

**Comment by vsoch** [comment]
Haha, that's literally the example I'm following too!

Could you share an example of how to generate a build tree (is this something that we can generate for the library here / with Python?) And I'm guessing this is streaming if you want to pipe events? Can you give me more details about SCons / languages? I'd like to help however I can - I'm not sure if codeart is relevant for you, or you are just interested in the particular issue to generate a visualization.

**Comment by vsoch** [comment]
Here is an example of what I'm currently testing - starting with a grid of randomly generated colors (this would be the RGB vectors generated for a code base / folder, etc.

![image](https://user-images.githubusercontent.com/814322/71835697-67d90380-306f-11ea-8a16-0ab19b9ee6ec.png)

Then sorting by rows and columns (sort of what I'm doing now, but I don't get the dimensions right)

![image](https://user-images.githubusercontent.com/814322/71835725-77f0e300-306f-11ea-89b9-7b9f106c4825.png)

Here is running a monte carlo reshuffling with 1 million iterations

![image](https://user-images.githubusercontent.com/814322/71837185-0adf4c80-3073-11ea-9350-ce6c2785a7b8.png)

5 million...

![image](https://user-images.githubusercontent.com/814322/71837545-ea63c200-3073-11ea-94b9-c68dc6ba41b4.png)

I'm likely going to need to let it run much longer to get a nice gradient.

**Comment by abitrolly** [comment]
Well, the SCons is able to dump static build tree [after](https://riptutorial.com/scons/topic/10170/scons-run-phases) building it. It is [made](https://riptutorial.com/scons/example/31163/inspecting-scons-phases) with `scons --tree=all`. And while SCons is doing this, nothing is being output. To demonstrate something larger I need to find some large codebase that is using SCons - maybe https://wiki.wesnoth.org/SCons - my last SCons project was https://github.com/Olga-Yakovleva/RHVoice and there are not many dependencies in the tree.

But large static tree is not as important as dynamic visualization of what SCons is doing. There are two parts in this process.

1. **Patching SCons to stream events**. Making it emit a message when a new node in a build tree is created. At first the message doesn't need to contain any information about the type of the node or even about its position - this is to make it easier to count all objects and find the proper place in SCons code to inject the emitter. The message doesn't even need to contain any info - just one sent message per one created object is fine for the start. The primary purpose of this step is to figure out the exchange protocol - so that SCons could run as fast as possible with and without vis attached, and also allow to attach vis at any time or even different vis apps during runtime to inspect if it creates objects and how many objects are created.

2. **Creating `netcanvas` for message vis**. `netcanvas` is a completely decoupled app that attaches to message stream and visualizes messages. The way how to visualize is completely free - it is for experimenting and easy adjustment for the task at hand - the concept is not to hardcode vis to specific message format, but let vis operate completely independently extracting whatever info it can from the messages. For example, the vis for empty messages from generated objects may look like a transparent grid with dynamically appearing cubes from left to right, top to bottom. The cubes can jump in to canvas rotating to show that the objects are alive in memory. If there are more information in the message, and vis can process it, the cubes can change color, spin and provide overlay info like in your `d3.js` tooltips. The `netcanvas` is meant to be a live coding tool.

**Comment by vsoch** [comment]
okay I wound up just doing sort by rows and columns taking hue into account (the sampling method was taking far too long and the result not too great). Here is the dummy output example for a set of dockerfiles https://vsoch.github.io/codeart-examples/dockerfiles/sorted/

I'll take some time to look at SCons sometime this week!

**Comment by vsoch** [comment]
@abitrolly can we open an issue on your repo (and ping me on it) for your last comment? I'm going to close the issue here because it's resolved.
